### PR TITLE
✨(frontend) new feedback link in header

### PR DESCRIPTION
**Pull request by manuhabitela**
this is just a link to an external url that is, for now, hardcoded as our deploys dont have frontend env vars right now

image

Will merge when the Grist is ready @CamCaz1 :innocent:

### CODE REVIEW

**Comment by CamCaz1** [comment]
@manuhabitela you're good to go :)  https://grist.incubateur.net/o/docs/hH7vmvWhV6qB/Visio2/f/4

**Comment by lebaudantoine** [comment]
coooool. Simple, efficient 🧠
I've two nit-picking comments 🥹😬
feel free to ignore it.

1. Could we center this element? Or increase the margin with the Meet title to match at least the one from the right side elements?
Capture d’écran 2024-07-25 à 22 41 15

2. On small screen, should we hide emoji/icons?
Capture d’écran 2024-07-25 à 22 40 53

**Comment by lebaudantoine** [comment]
💡 Brainsto (Let's open a dedicated issue) that would be dope having a 'finish' screen when you disconnect from a meeting, that would allow us collecting feedbacks / data.

Capture d’écran 2024-07-25 à 23 04 57

**Comment by manuhabitela** [comment]
Yeah camille suggested that too, i'll show the grist form link

**Pull request merged**
